### PR TITLE
Refactor 'uniq' function to use a Set.

### PR DESCRIPTION
**Pull request by andersonleite**
Hello Jeff, really nice lib!

Please take a look at this small refactor on the uniq function on the utils file.
All the tests are passing, including the linters. 
Thank you.

### CODE REVIEW

**Comment by jeffijoe** [comment]
Thanks for the PR!

Are there any numbers on the performance of both approaches?

**Comment by andersonleite** [comment]
Thanks for looking!

I didn't run a benchmark but here is probably a similar simulation:
[Unique Array Values in JavaScript](https://medium.com/@jakubsynowiec/unique-array-values-in-javascript-7c932682766c)

He starts with a loop using indefOf() that looks really similar to this case and then gets to this conclusion for using a Set:
> It turns out that this implementation is 50 times faster than any previous solution.

**Comment by andersonleite** [comment]
I was curios as well and did a quick "home made" benchmark with both approaches and yes, using a Set is way faster:

Number of initial  random elements: 100000
Performance before: **12.184682011604309**
Performance using set: **2.0349040031433105**

**Comment by jeffijoe** [comment]
Nice!

**Comment by jeffijoe** [comment]
Released in 5.0.1, thanks!

**Pull request merged**
