### PR TITLE
TypeScript definitions

### LINKED ISSUE #14: Add TypeScript Definition file (index.d.ts)
This looks like a cool DI container service. Could you include a TypeScript definition file (index.d.ts) for use with TS?

### PR DESCRIPTION
**Pull request by blove**
* Added index.d.ts TypeScript definitions.
* Created test/index.ts to test the TypeScript definitions.
* Test is compiled to /dist.
* Added ignore or root /dist directory to .gitignore.
* You can execute the test by swapping out the definitions with the real thing.
* Created /tsconfig.json for compiling TypeScript definition file test.
* A successful compilation == passed test.
* Added dependencies for mocha, mocha-typescript and DefinitelyTyped definitions for chai and node.

Resolves #14

### CODE REVIEW

**Comment by jeffijoe** [comment]
Great work! Almost there!

1. At what point do you run the TS tests?
2. Would you mind using single quotes and no semis to maintain consistency with the JS source?

**Comment by blove** [comment]
Jeff,

1. The declaration is tested simply by running the tsc command. I'm not sure if you want to add that to your package.json test script.
2. Sure; i'll commit an update for that.

**Comment by jeffijoe** [comment]
I'll add the package.json stuff after I merge this.

**Comment by blove** [comment]
@jeffijoe Ok, I committed the requested changes.

**Comment by jeffijoe** [comment]
Perfect!

**Comment by jeffijoe** [comment]
Thank you @blove! Great work!

**Comment by blove** [comment]
Thanks @jeffijoe. I am enjoying using awilix and the awilix-express middleware in my Express app! 👍 

I don't know if you have used Angular (2.x+), but their dependency injection framework is pretty sweet. It uses decorators (like @Injectable()) and type declarations in class constructors to do DI. Would love to see Awilix move to something like this for TS. Though, maybe that would be a separate project from Awilix. Just throwing that out there. :)

**Comment by jeffijoe** [comment]
Yeah there are already libraries that do just that with TS - however I would like Awilix to not rely on decorators or anything that would require you to import Awilix in your business code.

Example:

```
export default class UserService {
  constructor ({ userRepository }) {
    this.userRepo = userRepository
  }
}
```

Nothing in that code depends on Awilix at all, your business logic should be independent of DI frameworks.

At least that's how I see it. 😄

**Comment by jeffijoe** [comment]
Hey quick Q, how come I'm seeing this error in the tests?

image

**Comment by jeffijoe** [comment]
Pushed 2.2.4 to npm.

**Comment by blove** [comment]
Interesting. I don't have an issue compiling via <code>tsc</code>, nor do I see that error in VS Code. Are you using webstorm?

Maybe the <code>cradle</code> property of the <code>AwilixContainer</code> class should simply be <code>any</code>. I currently have it as an <code>Object</code>, whose keys are <code>string</code>s and the value can be <code>any</code>. I did try to define this as a <code>Proxy</code> but could not get that to work.  😕

**Comment by jeffijoe** [comment]
Yeah I'd say `any` but it's probably just Sublime Text that's the issue here. Oh well. 😄

**Comment by blove** [comment]
I'm happy to change it to <code>any</code> or you can.

**Comment by jeffijoe** [comment]
It's probably a Sublime TS bug. I think what you have is more correct.

**Comment by blove** [comment]
Ok, agreed, we'll leave it as is.

**Pull request merged**
