### PR TITLE
fix(container): createScope return defaults to original container

### LINKED ISSUE #178: createScope should return container type by default
https://github.com/jeffijoe/awilix/blob/7625dd94e6697621aad21d295afa13c0331db2bf/src/container.ts#L45

If you create a scoped container without a generic type, the return type of the new container is `any`

```ts
interface Foo {
  foo: string
}
const container = createContainer<Foo>()

// scoped has AwilixContainer<any> type
const scoped = container.createScope()
```

I think the type should be:

```ts
createScope<T extends object = {}>(): AwilixContainer<Cradle & T>
```

### PR DESCRIPTION
**Pull request by moltar**
Closes #178

### CODE REVIEW

**Comment by jeffijoe** [comment]
Looks good! Can I ask you to do a few small things in this PR as well?

* Remove `yarn.lock`, run `npm install` to switch to NPM. Yarn seems to have gone off the deep end.
* `npm i -D rimraf` to fix #179 
* Run `npx npm-check --skip-unused -u` to upgrade all packages to latest, run lint and cover (I expect `prettier@2` will format all files, that's fine)

**Comment by moltar** [comment]
Seems like outside the scope of a PR.

Maybe we should do a separate PR?

**Comment by moltar** [comment]
And for updates, wouldn't it better to setup @renovatebot?

**Comment by jeffijoe** [comment]
I'm fine with it being the same PR, the update will go out as a single release anyway, I am just trying to cut down on needless bureaucratic work.

I haven't set up automated releases for Awilix because I've had some issues with it in the past, and I also don't want to release a new version every 12 hours because of package updates 🤣

However anytime there are actual changes that need to be released, I update the deps before doing so.

**Pull request merged**
