### PR TITLE
added support of cyclic dependencies

### PR DESCRIPTION
**Pull request by PShahen**

### CODE REVIEW

**Comment by jeffijoe** [comment]
Hi @PShahen!

The `lazy` resolver actually supports cyclic dependencies, just FYI! 😄

**Comment by PShahen** [comment]
Hi @jeffijoe 
Thanks for the information. However the issue for us is that we have a project with many classes  created with `CLASSIC` injection mode so we can't use `lazy` resolver without doing refactoring, can we ?

**Comment by jeffijoe** [comment]
Sure you can, `lazy` just wraps the dependency in a `Proxy` which resolves the dependency whenever a property gets accessed.

**Comment by jeffijoe** [comment]
Hmm, I thought I added `lazy` but I guess not! It's a pretty simple resolver though. From the top of my head:

```js
function lazy(resolver) {
  let resolved = null
  return createBuildResolver({
    resolve(container) {
      return new Proxy({}, {
        get(name) {
          if (resolved) {
            return resolved.value[name]
          }
          resolved = {
            value: resolver.resolve(container)
          }
          return resolved.value[name]
        }
      }) 
    }
  })
}
```

**Comment by PShahen** [comment]
thanks @jeffijoe . I'll try this solution.
I feel the same way about cyclic dependencies. but we've quite a lot of cases when there is cyclic  dependencies chain like `A->B->C->D-A` and I guess many people may have this problem when integrating DI to existing project

**Pull request closed without merging**
